<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class WordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('words')->insert([
            [   "id"            => 1,
                "word"          => "abandon",
                "pronounce"     => "/ə'bændən/",
                "means"         => "bỏ, từ bỏ",
        ],
        [   "id"            => 2,
                "word"          => "abandoned",
                "pronounce"     => "/ə'bændənd/",
                "means"         => "bị bỏ rơi, bị ruồng bỏ",
                ],
        [   "id"            => 3,
                "word"          => "ability",
                "pronounce"     => "/ə'biliti/",
                "means"         => "khả năng, năng lực",
                ],
        [   "id"            => 4,
                "word"          => "able",
                "pronounce"     => "/'eibl/",
                "means"         => "có năng lực, có tài",
                ],
        [   "id"            => 5,
                "word"          => "unable",
                "pronounce"     => "/'ʌn'eibl/",
                "means"         => "không có năng lực, không có tài",
                ],
        [   "id"            => 6,
                "word"          => "about",
                "pronounce"     => "/ə'baut/",
                "means"         => "khoảng, về",
                ],
        [   "id"            => 7,
                "word"          => "above",
                "pronounce"     => "/ə'bʌv/",
                "means"         => "ở trên, lên trên",
                ],
        [   "id"            => 8,
                "word"          => "abroad",
                "pronounce"     => "/ə'brɔ:d/",
                "means"         => "ở, ra nước ngoài, ngoài trời",
                ],
        [   "id"            => 9,
                "word"          => "absence",
                "pronounce"     => "/'æbsəns/",
                "means"         => "sự vắng mặt",
                ],
        [   "id"            => 10,
                "word"          => "absent",
                "pronounce"     => "/'æbsənt/",
                "means"         => "vắng mặt, nghỉ",
                ],
        [   "id"            => 11,
                "word"          => "absolute",
                "pronounce"     => "/'æbsəlu:t/",
                "means"         => "tuyệt đối, hoàn toàn",
                ],
        [   "id"            => 12,
                "word"          => "absolutely",
                "pronounce"     => "/'æbsəlu:tli/",
                "means"         => "tuyệt đối, hoàn toàn",
                ],
        [   "id"            => 13,
                "word"          => "absorb",
                "pronounce"     => "/əb'sɔ:b/",
                "means"         => "thu hút, hấp thu, lôi cuốn",
                ],
        [   "id"            => 14,
                "word"          => "academic",
                "pronounce"     => "/,ækə'demik/",
                "means"         => "thuộc học viện, ĐH, viện hàn lâm",
                ],
        [   "id"            => 15,
                "word"          => "accent",
                "pronounce"     => "/'æksənt/",
                "means"         => "trọng âm, dấu trọng âm",
                ],
        [   "id"            => 16,
                "word"          => "accept",
                "pronounce"     => "/ək'sept/",
                "means"         => "chấp nhận, chấp thuận",
                ],
        [   "id"            => 17,
                "word"          => "acceptable",
                "pronounce"     => "/ək'septəbl/",
                "means"         => "có thể chấp nhận, chấp thuận",
                ],
        [   "id"            => 18,
                "word"          => "unacceptable",
                "pronounce"     => "/'ʌnək'septəbl/",
                "means"         => "",
                ],
        [   "id"            => 19,
                "word"          => "access",
                "pronounce"     => "/'ækses/",
                "means"         => "lối, cửa, đường vào",
                ],
        [   "id"            => 20,
                "word"          => "accident",
                "pronounce"     => "/'æksidənt/",
                "means"         => "tai nạn, rủi ro",
                ],
        [   "id"            => 21,
                "word"          => "accidental",
                "pronounce"     => "/,æksi'dentl/",
                "means"         => "tình cờ, bất ngờ",
                ],
        [   "id"            => 22,
                "word"          => "accidentally",
                "pronounce"     => "/,æksi'dentəli/",
                "means"         => "tình cờ, ngẫu nhiên",
                ],
        [   "id"            => 23,
                "word"          => "accommodation",
                "pronounce"     => "/ə,kɔmə'deiʃn/",
                "means"         => "sự thích nghi, điều tiết",
                ],
        [   "id"            => 24,
                "word"          => "accompany",
                "pronounce"     => "/ə'kʌmpəni/",
                "means"         => "đi theo, đi cùng, kèm theo",
                ],
        [   "id"            => 25,
                "word"          => "abuse",
                "pronounce"     => "/ə'bju:s/",
                "means"         => "lộng hành, lạm dụng",
                ],
        [   "id"            => 26,
                "word"          => "account",
                "pronounce"     => "/ə'kaunt/",
                "means"         => "tài khoản, kế toán; tính toán, tính đến",
                ],
        [   "id"            => 27,
                "word"          => "accurate",
                "pronounce"     => "/'ækjurit/",
                "means"         => "đúng đắn, chính xác, xác đáng",
                ],
        [   "id"            => 28,
                "word"          => "accurately",
                "pronounce"     => "/'ækjuritli/",
                "means"         => "đúng đắn, chính xác",
                ],
        [   "id"            => 29,
                "word"          => "accuse",
                "pronounce"     => "/ə'kju:z/",
                "means"         => "tố cáo, buộc tội, kết tội",
                ],
        [   "id"            => 30,
                "word"          => "achieve",
                "pronounce"     => "/ə'tʃi:v/",
                "means"         => "đạt được, dành được",
                ],
        [   "id"            => 31,
                "word"          => "achievement",
                "pronounce"     => "/ə'tʃi:vmənt/",
                "means"         => "thành tích, thành tựu",
                ],
        [   "id"            => 32,
                "word"          => "acid",
                "pronounce"     => "/'æsid/",
                "means"         => "axit",
                ],
        [   "id"            => 33,
                "word"          => "acknowledge",
                "pronounce"     => "/ək'nɔlidʤ/",
                "means"         => "công nhận, thừa nhận",
                ],
        [   "id"            => 34,
                "word"          => "acquire",
                "pronounce"     => "/ə'kwaiə/",
                "means"         => "dành được, đạt được, kiếm được",
                ],
        [   "id"            => 35,
                "word"          => "across",
                "pronounce"     => "/ə'krɔs/",
                "means"         => "qua, ngang qua",
                ],
        [   "id"            => 36,
                "word"          => "act",
                "pronounce"     => "/ækt/",
                "means"         => "hành động, hành vi, cử chỉ, đối xử",
                ],
        [   "id"            => 37,
                "word"          => "action",
                "pronounce"     => "/'ækʃn/",
                "means"         => "hành động, hành vi, tác động",
                ],
        [   "id"            => 38,
                "word"          => "active",
                "pronounce"     => "/'æktiv/",
                "means"         => "tích cực hoạt động, nhanh nhẹn",
                ],
        [   "id"            => 39,
                "word"          => "actively",
                "pronounce"     => "/'æktivli/",
                "means"         => "tích cực",
                ],
        [   "id"            => 40,
                "word"          => "activity",
                "pronounce"     => "/æk'tiviti/",
                "means"         => "",
                ],
        [   "id"            => 41,
                "word"          => "actor, actress",
                "pronounce"     => "/'æktə/ /'æktris/",
                "means"         => "diễn viên",
                ],
        [   "id"            => 42,
                "word"          => "actual",
                "pronounce"     => "/'æktjuəl/",
                "means"         => "thực tế, có thật",
                ],
        [   "id"            => 43,
                "word"          => "actually",
                "pronounce"     => "/'æktjuəli/",
                "means"         => "hiện nay, hiện tại",
                ],
        [   "id"            => 44,
                "word"          => "advertisement",
                "pronounce"     => "/əd'və:tismənt/",
                "means"         => "quảng cáo",
                ],
        [   "id"            => 45,
                "word"          => "adapt",
                "pronounce"     => "/ə'dæpt/",
                "means"         => "tra, lắp vào",
                ],
        [   "id"            => 46,
                "word"          => "add",
                "pronounce"     => "/æd/",
                "means"         => "cộng, thêm vào",
                ],
        [   "id"            => 47,
                "word"          => "addition",
                "pronounce"     => "/ə'diʃn/",
                "means"         => "tính cộng, phép cộng",
                ],
        [   "id"            => 48,
                "word"          => "additional",
                "pronounce"     => "/ə'diʃənl/",
                "means"         => "thêm vào, tăng thêm",
                ],
        [   "id"            => 49,
                "word"          => "address",
                "pronounce"     => "/ə'dres/",
                "means"         => "địa chỉ, đề địa chỉ",
                ],
        [   "id"            => 50,
                "word"          => "adequate",
                "pronounce"     => "/'ædikwit/",
                "means"         => "đầy, đầy đủ",
                ],
        [   "id"            => 51,
                "word"          => "adequately",
                "pronounce"     => "/'ædikwitli/",
                "means"         => "tương xứng, thỏa đáng",
                ],
        [   "id"            => 52,
                "word"          => "adjust",
                "pronounce"     => "/ə'dʤʌst/",
                "means"         => "sửa lại cho đúng, điều chỉnh",
                ],
        [   "id"            => 53,
                "word"          => "admiration",
                "pronounce"     => "/,ædmə'reiʃn/",
                "means"         => "sự khâm phục,người kp, thán phục",
                ],
        [   "id"            => 54,
                "word"          => "admire",
                "pronounce"     => "/əd'maiə/",
                "means"         => "khâm phục, thán phục",
                ],
        [   "id"            => 55,
                "word"          => "admit",
                "pronounce"     => "/əd'mit/",
                "means"         => "nhận vào, cho vào, kết hợp",
                ],

        [   "id"            => 56,
                "word"          => "adopt",
                "pronounce"     => "/ə'dɔpt/",
                "means"         => "nhận làm con nuôi, bố mẹ nuôi",
                ],
        [   "id"            => 57,
                "word"          => "adult",
                "pronounce"     => "/'ædʌlt/",
                "means"         => "người lớn, người trưởng thành; trưởng thành",
                ],
        [   "id"            => 58,
                "word"          => "advance",
                "pronounce"     => "/əd'vɑ:ns/",
                "means"         => "sự tiến bộ, tiến lên; đưa lên, đề xuất",
                ],
        [   "id"            => 59,
                "word"          => "advanced",
                "pronounce"     => "/əd'vɑ:nst/",
                "means"         => "tiên tiến, tiến bộ, cấp cao",
                ],
        [   "id"            => 60,
                "word"          => "advantage",
                "pronounce"     => "/əb'vɑ:ntidʤ/",
                "means"         => "sự thuận lợi, lợi ích, lợi thế",
                ],
        [   "id"            => 61,
                "word"          => "adventure",
                "pronounce"     => "/əd'ventʃə/",
                "means"         => "sự phiêu lưu, mạo hiểm",
                ],
        [   "id"            => 62,
                "word"          => "advertise",
                "pronounce"     => "/'ædvətaiz/",
                "means"         => "báo cho biết, báo cho biết trước",
                ],
        [   "id"            => 63,
                "word"          => "advertising",
                "pronounce"     => "/ˈæd.və.taɪ.zɪŋ/",
                "means"         => "sự quảng cáo, nghề quảng cáo",
                ],
        [   "id"            => 64,
                "word"          => "advice",
                "pronounce"     => "/əd'vais/",
                "means"         => "lời khuyên, lời chỉ bảo",
                ],
        [   "id"            => 65,
                "word"          => "advise",
                "pronounce"     => "/əd'vaiz/",
                "means"         => "khuyên, khuyên bảo, răn bảo",
                ],
        [   "id"            => 66,
                "word"          => "affair",
                "pronounce"     => "/ə'feə/",
                "means"         => "việc",
                ],
        [   "id"            => 67,
                "word"          => "affect",
                "pronounce"     => "/ə'fekt/",
                "means"         => "làm ảnh hưởng, tác động đến",
                ],
        [   "id"            => 68,
                "word"          => "afford",
                "pronounce"     => "/ə'fɔ:d/",
                "means"         => "có thể, có đủ khả năng, điều kiện (làm gì)",
                ],
        [   "id"            => 69,
                "word"          => "afraid",
                "pronounce"     => "/ə'freid/",
                "means"         => "sợ, sợ hãi, hoảng sợ",
                ],
        [   "id"            => 70,
                "word"          => "after",
                "pronounce"     => "/'ɑ:ftə/",
                "means"         => "sau, đằng sau, sau khi",
                ],
        [   "id"            => 71,
                "word"          => "afternoon",
                "pronounce"     => "/'ɑ:ftə'nu:n/",
                "means"         => "buổi chiều",
                ],
        [   "id"            => 72,
                "word"          => "afterwards",
                "pronounce"     => "/'ɑ:ftəwəd/",
                "means"         => "sau này, về sau, rồi thì, sau đấy",
                ],
        [   "id"            => 73,
                "word"          => "again",
                "pronounce"     => "/ə'gen/",
                "means"         => "lại, nữa, lần nữa",
                ],
        [   "id"            => 74,
                "word"          => "against",
                "pronounce"     => "/ə'geinst/",
                "means"         => "chống lại, phản đối",
                ],
        [   "id"            => 75,
                "word"          => "age",
                "pronounce"     => "/eidʤ/",
                "means"         => "tuổi",
                ],
        [   "id"            => 76,
                "word"          => "aged",
                "pronounce"     => "/'eidʤid/",
                "means"         => "già đi",
                ],
        [   "id"            => 77,
                "word"          => "agency",
                "pronounce"     => "/'eidʤənsi/",
                "means"         => "tác dụng, lực; môi giới, trung gian",
                ],
        [   "id"            => 78,
                "word"          => "agent",
                "pronounce"     => "/'eidʤənt/",
                "means"         => "đại lý, tác nhân",
                ],
        [   "id"            => 79,
                "word"          => "aggressive",
                "pronounce"     => "/ə'gresiv/",
                "means"         => "xâm lược, hung hăng (US: xông xáo)",
                ],
        [   "id"            => 80,
                "word"          => "ago",
                "pronounce"     => "/ə'gou/",
                "means"         => "trước đây",
                ],
        [   "id"            => 81,
                "word"          => "agree",
                "pronounce"     => "/ə'gri:/",
                "means"         => "đồng ý, tán thành",
                ],
        [   "id"            => 82,
                "word"          => "agreement",
                "pronounce"     => "/ə'gri:mənt/",
                "means"         => "sự đồng ý, tán thành; hiệp định, hợp đồng",
                ],
        [   "id"            => 83,
                "word"          => "ahead",
                "pronounce"     => "/ə'hed/ trước",
                "means"         => "về phía trước",
                ],
        [   "id"            => 84,
                "word"          => "aid",
                "pronounce"     => "/eid/",
                "means"         => "sự giúp đỡ; thêm vào, phụ vào",
                ],
        [   "id"            => 85,
                "word"          => "aim",
                "pronounce"     => "/eim/",
                "means"         => "sự nhắm (bắn), mục tiêu, ý định; nhắm, tập trung, hướng vào",
                ],
        [   "id"            => 86,
                "word"          => "air",
                "pronounce"     => "/eə/",
                "means"         => "không khí, bầu không khí, không gian",
                ],
        [   "id"            => 87,
                "word"          => "aircraft",
                "pronounce"     => "/'eəkrɑ:ft/",
                "means"         => "máy bay, khí cầu",
                ],
        [   "id"            => 88,
                "word"          => "airport",
                "pronounce"     => "/ˈeə.pɔːt/",
                "means"         => "sân bay, phi trường",
                ],
        [   "id"            => 89,
                "word"          => "alarm",
                "pronounce"     => "/ə'lɑ:m/",
                "means"         => "báo động, báo nguy",
                ],
        [   "id"            => 90,
                "word"          => "alarming",
                "pronounce"     => "/ə'lɑ:miɳ/",
                "means"         => "làm lo sợ, làm hốt hoảng, làm sợ hãi",
                ],
        [   "id"            => 91,
                "word"          => "alcohol",
                "pronounce"     => "/'ælkəhɔl/",
                "means"         => "rượu cồn",
                ],
        [   "id"            => 92,
                "word"          => "alcoholic",
                "pronounce"     => "/,ælkə'hɔlik/",
                "means"         => "rượu; người nghiện rượu",
                ],
        [   "id"            => 93,
                "word"          => "alive",
                "pronounce"     => "/ə'laiv/",
                "means"         => "sống, vẫn còn sống, còn tồn tại",
                ],
        [   "id"            => 94,
                "word"          => "all",
                "pronounce"     => "/ɔ:l/",
                "means"         => "tất cả",
                ],
        [   "id"            => 95,
                "word"          => "allow",
                "pronounce"     => "/ə'lau/",
                "means"         => "cho phép, để cho",
                ],
        [   "id"            => 96,
                "word"          => "all right",
                "pronounce"     => "/'ɔ:l'rait/",
                "means"         => "tốt, ổn, khỏe mạnh; được",
                ],
        [   "id"            => 97,
                "word"          => "ally",
                "pronounce"     => "/'æli/",
                "means"         => "nước đồng minh, liên minh; liên kết, lien minh, kết thông gia",
                ],
        [   "id"            => 98,
                "word"          => "allied",
                "pronounce"     => "/ə'laid/",
                "means"         => "liên minh, đồng minh, thông gia",
                ],
        [   "id"            => 99,
                "word"          => "almost",
                "pronounce"     => "/'ɔ:lmoust/",
                "means"         => "hầu như, gần như",
                ],
        [   "id"            => 100,
                "word"          => "alone",
                "pronounce"     => "/ə'loun/",
                "means"         => "cô đơn, một mình",
                ],
    
        ]);
    }
}
